### ISSUE TITLE
Peak files

### ISSUE THREAD

**Issue by chernovsergey** [ying-w/chipseq-compare#1]
Hi @ying-w 

I'm thanking you for MAnorm improvement!!!!!! You made my day!

But, please, could you explain me the meaning of files `gr_peak.bed` and  `er_peak.bed` in MAnorm3.sh? 
I have the following files for each condition:
- replicate1
- replicate2
- control for replicate1
- control for replicate2

And I need to compare two such conditions, but stuck in choosing gr_peak and er_peak. How can I get this files?

Sorry, this is not my major and I'm learning. 

Thank you a lot for the answer, Sergey

**Comment by ying-w** [comment]
you will need to first identify the regions of interest for your treatment and replicate (the process of 'peak calling'). The gr_peak.bed and er_peak.bed are examples of peak caller output. You will have to feed your reads into a peak caller. Popular peak callers include [macs](https://github.com/taoliu/MACS) and [homer](http://homer.salk.edu/homer/index.html), since you have replicates, i would recommend using an IDR method (you can find more info about it [here](https://github.com/roryk/spp-idr) and [here](https://github.com/nboley/idr))
